### ISSUE TITLE
Suggestion: change naming

### ISSUE THREAD

**Issue by serkandurusoy** [dovrosenberg/meteor-astronomy-displayFormat#1]
I think `format` should be renamed as `displayFormat` so that:
- it is semantically better suited
- it does not conflict with a possible future `format` definition that pertains to the data type of the field

``` javascript
Item = Astro.Class({
  name: 'Item',
  collection: Items,
  fields: {
     price: {
        type: 'number',
        // format: 'currency'
        displayFormat: 'currency'
    }
  }
});
```

**Comment by dovrosenberg** [comment]
I'm not opposed to changing it, though what do you imagine the "future format definition" to do that Astronomy's current "type" does not?

**Comment by serkandurusoy** [comment]
`format` is too generic a namespace to occupy by an extension and I believe it should be reserved for the core. 

I honestly can't know what the future holds. But if something like that happens, it would be hard to introduce an API change that late down the line. So, I guess this is about being safe than sorry.

Otherwise, kudos on your work. Nice package!

**Comment by dovrosenberg** [comment]
Fair enough.  Done - version 1.0.0 due to the breaking change.

**Comment by serkandurusoy** [comment]
:+1:
